export const eventAgeGroupValues = [
  "under_13",
  "ages_13_17",
  "ages_18_24",
  "ages_25_59",
  "ages_60_plus",
  "mixed_ages",
] as const;

export const eventAgeGroupLabels: Record<
  (typeof eventAgeGroupValues)[number],
  string
> = {
  under_13: "Under 13 (child with parent/guardian)",
  ages_13_17: "13–17 (teen)",
  ages_18_24: "18–24 (young adult)",
  ages_25_59: "25–59 (adult)",
  ages_60_plus: "60+ (older adult)",
  mixed_ages: "Mixed ages (family or group)",
};

export const eventActivityValues = [
  "learning_workshops",
  "youth_mentorship",
  "sports_wellness",
  "community_service",
  "business_livelihoods",
  "digital_skills",
  "environment",
  "arts_culture",
  "health_wellbeing",
  "intergenerational_activities",
  "open_to_any_activity",
  "other",
] as const;

export const eventActivityLabels: Record<
  (typeof eventActivityValues)[number],
  string
> = {
  learning_workshops: "Learning and practical workshops",
  youth_mentorship: "Youth mentorship and leadership",
  sports_wellness: "Sports, movement, and wellness",
  community_service: "Community service and volunteering",
  business_livelihoods: "Small business and livelihood skills",
  digital_skills: "Digital and technology skills",
  environment: "Environment and conservation",
  arts_culture: "Arts, culture, and creative activities",
  health_wellbeing: "Health and wellbeing",
  intergenerational_activities: "Family and intergenerational activities",
  open_to_any_activity: "I’m open to any activity",
  other: "Something else",
};

export const kenyaCounties = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang’a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
] as const;
