export const eventAgeGroupValues = [
  "under_13",
  "ages_13_17",
  "ages_18_24",
  "ages_25_59",
  "ages_60_plus",
  "mixed_ages",
] as const;

export const eventActivityValues = [
  "learning_workshops",
  "youth_mentorship",
  "sports_wellness",
  "community_service",
  "business_livelihoods",
  "digital_skills",
  "environment",
  "arts_culture",
  "health_wellbeing",
  "intergenerational_activities",
  "open_to_any_activity",
  "other",
] as const;

export const kenyaCounties = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
] as const;
